language: nix

env:
  global:
    - CACHIX_CACHE=sikmir
    - NUR_REPO=sikmir

jobs:
  include:
    - name: "nixpkgs-unstable"
      env: NIX_CHANNEL=https://nixos.org/channels/nixpkgs-unstable
    - name: "nixos-unstable"
      env: NIX_CHANNEL=https://nixos.org/channels/nixos-unstable

install:
  - nix --version
  - if [ -n "${CACHIX_CACHE}" ]; then travis_retry nix-channel --update; fi
  - if [ -n "${CACHIX_CACHE}" ]; then nix-env -iA cachix -f https://cachix.org/api/v1/install; fi
  - if [ -n "${CACHIX_CACHE}" ]; then cachix use "${CACHIX_CACHE}"; fi
  - nix-channel --add "${NIX_CHANNEL}" nixpkgs
  - travis_retry nix-channel --update

script:
  - nix-build ci.nix -A buildOutputs
  - nix eval -f default.nix 'lib'
  - nix eval -f default.nix 'modules'
  - nix eval -f default.nix 'overlays'

after_success:
  - if [ -n "${CACHIX_CACHE}" ]; then nix-build ci.nix -A cacheOutputs | cachix push "${CACHIX_CACHE}"; fi
  - if [ "false" = "${TRAVIS_PULL_REQUEST}" -a "master" = "${TRAVIS_BRANCH}" ]; then
    curl -XPOST "https://nur-update.herokuapp.com/update?repo=${NUR_REPO}"; fi
